export const stateEnum: any = {
  Acre: 1,
  Alagoas: 2,
  Amapá: 3,
  Amazonas: 4,
  Bahia: 5,
  Ceará: 6,
  "Distrito Federal": 7,
  "Espírito Santo": 8,
  Goiás: 9,
  Maranhão: 10,
  "Mato Grosso": 11,
  "Mato Grosso do Sul": 12,
  "Minas Gerais": 13,
  Paraná: 14,
  Paraíba: 15,
  Pará: 16,
  Pernambuco: 17,
  Piauí: 18,
  "Rio de Janeiro": 19,
  "Rio Grande do Norte": 20,
  "Rio Grande do Sul": 21,
  Rondônia: 22,
  Roraima: 23,
  "Santa Catarina": 24,
  Sergipe: 25,
  "São Paulo": 26,
  Tocantins: 27,
};

export const statesList = [
  { value: 1, label: "Acre" },
  { value: 2, label: "Alagoas" },
  { value: 3, label: "Amapá" },
  { value: 4, label: "Amazonas" },
  { value: 5, label: "Bahia" },
  { value: 6, label: "Ceará" },
  { value: 7, label: "Distrito Federal" },
  { value: 8, label: "Espírito Santo" },
  { value: 9, label: "Goiás" },
  { value: 10, label: "Maranhão" },
  { value: 11, label: "Mato Grosso" },
  { value: 12, label: "Mato Grosso do Sul" },
  { value: 13, label: "Minas Gerais" },
  { value: 14, label: "Paraná" },
  { value: 15, label: "Paraíba" },
  { value: 16, label: "Pará" },
  { value: 17, label: "Pernambuco" },
  { value: 18, label: "Piauí" },
  { value: 19, label: "Rio de Janeiro" },
  { value: 20, label: "Rio Grande do Norte" },
  { value: 21, label: "Rio Grande do Sul" },
  { value: 22, label: "Rondônia" },
  { value: 23, label: "Roraima" },
  { value: 24, label: "Santa Catarina" },
  { value: 25, label: "Sergipe" },
  { value: 26, label: "São Paulo" },
  { value: 27, label: "Tocantins" },
];
